displayName=Equipment Inspector
author=botanicvelious
support=https://github.com/Equipment-Inspector/Equipment-Inspector
description=Inspect other players equipment.
tags=equipment,items,gear
version=1.3.0
plugins=equipmentinspector.EquipmentInspectorPlugin
build=standard
